name: cpf_cnpj_validator
description: A lib to validate CPF and CNPJ numbers.
version: 1.0.2
author: Leonardo Caldas <leonardo.ferreira.caldas@gmail.com>
homepage: https://github.com/leonardocaldas/flutter-cpf-cnpj-validator

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter